
ESCENARIES=All_scenarios.csv
SC1=Scenario_1_Emergencies_Lorca_Earthquake.csv
SC2=Scenario_2_Infrastructure_monitoring.csv
#SC3=Scenario_3_South_West_England.csv
#SC4=Scenario_4_Precision_Agriculture_Argentina.csv
#SC5=Scenario_5_6_Basemap_Worldwide.csv

all:
	python setDatabase.py localhost All_Scenarios.py $(SC1) $(SC2) $(SC3) $(SC4)
